# Generated by Django 5.2.4 on 2025-08-31 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_unpublish_product', 'Can unpublish product')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
